[package]
versioned_files = ["Cargo.toml"]
changelog = "CHANGELOG.md"

[[package.assets]]
path = "htb-linux-x86_64.tar.gz"

[[package.assets]]
path = "htb-linux-aarch64.tar.gz"

[[package.assets]]
path = "htb-macos-x86_64.tar.gz"

[[package.assets]]
path = "htb-macos-aarch64.tar.gz"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git add -A && git commit -m 'chore: prepare release'"

[[workflows.steps]]
type = "Release"
